#!/usr/bin/env bash
#
# Generate secure random database password for Obsidian Graph MCP server
#
# This script:
# 1. Generates a cryptographically random 48-character password
# 2. Updates configs/obsidian-graph/.env.instance
# 3. Creates docker-compose.override.yml with environment variable
# 4. Validates synchronization between files
#
# Usage:
#   ./scripts/generate-db-password.sh [--force]
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
CONFIG_DIR="$PROJECT_ROOT/configs/obsidian-graph"
ENV_FILE="$CONFIG_DIR/.env.instance"
OVERRIDE_FILE="$PROJECT_ROOT/docker-compose.override.yml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Generate secure random password (48 chars: alphanumeric)
generate_password() {
    # Use openssl for reliable password generation
    openssl rand -base64 36 | tr -dc 'A-Za-z0-9' | head -c 48
}

echo "🔐 Obsidian Graph - Database Password Generator"
echo "=============================================="

# Check if password already exists
if [[ -f "$ENV_FILE" ]]; then
    CURRENT_PW=$(grep "^POSTGRES_PASSWORD=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2)
    if [[ -n "$CURRENT_PW" && "$CURRENT_PW" != "changeme" && "$CURRENT_PW" != "your_generated_password_here" ]]; then
        if [[ "${1:-}" != "--force" ]]; then
            echo -e "${YELLOW}⚠️  Password already exists in $ENV_FILE${NC}"
            echo "Use --force to regenerate (will require container restart)"
            exit 0
        fi
        echo -e "${YELLOW}⚠️  Regenerating password (--force flag detected)${NC}"
    fi
fi

# Generate new password
NEW_PASSWORD=$(generate_password)
echo -e "${GREEN}✓${NC} Generated 48-character password"

# Update or create .env.instance
if [[ ! -f "$ENV_FILE" ]]; then
    # Create from example
    if [[ -f "$CONFIG_DIR/.env.instance.example" ]]; then
        cp "$CONFIG_DIR/.env.instance.example" "$ENV_FILE"
        echo -e "${GREEN}✓${NC} Created $ENV_FILE from example"
    else
        echo -e "${RED}✗${NC} Error: $CONFIG_DIR/.env.instance.example not found"
        exit 1
    fi
fi

# Update password in env file (macOS and Linux compatible)
if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/^POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=$NEW_PASSWORD/" "$ENV_FILE"
else
    sed -i "s/^POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=$NEW_PASSWORD/" "$ENV_FILE"
fi

echo -e "${GREEN}✓${NC} Updated $ENV_FILE"

# Create docker-compose.override.yml to override hardcoded password
cat > "$OVERRIDE_FILE" << EOF
# Auto-generated by servers/obsidian-graph/scripts/generate-db-password.sh
# This file overrides the hardcoded password in docker-compose.yml
# DO NOT commit this file to version control!
version: '3.8'

services:
  mcp-obsidian-graph-pgvector:
    environment:
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
EOF

echo -e "${GREEN}✓${NC} Created $OVERRIDE_FILE"

# Verify synchronization
echo ""
echo "🔍 Verifying configuration..."

# Check both files reference the same password mechanism
if grep -q "POSTGRES_PASSWORD: \\\${POSTGRES_PASSWORD}" "$OVERRIDE_FILE"; then
    echo -e "${GREEN}✓${NC} docker-compose.override.yml references environment variable"
else
    echo -e "${RED}✗${NC} docker-compose.override.yml not properly configured"
    exit 1
fi

if grep -q "^POSTGRES_PASSWORD=$NEW_PASSWORD" "$ENV_FILE"; then
    echo -e "${GREEN}✓${NC} .env.instance contains new password"
else
    echo -e "${RED}✗${NC} .env.instance not properly updated"
    exit 1
fi

echo ""
echo -e "${GREEN}✅ Password generation complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Export password for docker-compose:"
echo "     export POSTGRES_PASSWORD=\$(grep '^POSTGRES_PASSWORD=' $ENV_FILE | cut -d'=' -f2)"
echo "  2. Restart containers:"
echo "     docker-compose down && docker-compose up -d obsidian-graph"
echo "  3. Verify connection:"
echo "     docker logs mcp-obsidian-graph"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT: Never commit .env.instance or docker-compose.override.yml to version control!${NC}"
